Fix compile error in mod_diskuse.c when shared object is selected.
Fixing an issue where mod_diskuse.c will fail to compile if shared
object module mode for contributed modules is selected.  In other
words, when the PR_SHARED_MODULE is defined then an ordering problem
will manifest itself causing the following error:

  mod_diskuse.c: In function ‘diskuse_mod_unload_ev’:
  mod_diskuse.c:300: error: ‘diskuse_module’ undeclared (first use in this function)
  mod_diskuse.c:300: error: (Each undeclared identifier is reported only once
  mod_diskuse.c:300: error: for each function it appears in.)
  mod_diskuse.c: In function ‘diskuse_init’:
  mod_diskuse.c:311: error: ‘diskuse_module’ undeclared (first use in this function)
  make[2]: *** [mod_diskuse.la] Error 1
  make[2]: Leaving directory `/root/Sandbox/proftpd/proftpd-dfsg-1.3.4a/modules'
  make[1]: *** [modules] Error 2
  make[1]: Leaving directory `/root/Sandbox/proftpd/proftpd-dfsg-1.3.4a'
  make: *** [build-stamp] Error 2

Signed-off-by: Krzysztof Wilczynski <krzysztof.wilczynski@linux.com>